/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-05-05

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32f10x.h"

/* Private macro */
#define nOE_PORT GPIOB
#define nOE GPIO_Pin_5

#define Sx_PORT GPIOB
#define S0 GPIO_Pin_6
#define S1 GPIO_Pin_7
#define S2 GPIO_Pin_8
#define S3 GPIO_Pin_9

#define PWR_DOWN() GPIO_ResetBits(Sx_PORT,S0);GPIO_ResetBits(Sx_PORT,S1);
#define FREQ_SCAL_2p() GPIO_ResetBits(Sx_PORT,S0);GPIO_SetBits(Sx_PORT,S1);
#define FREQ_SCAL_20p() GPIO_SetBits(Sx_PORT,S0);GPIO_ResetBits(Sx_PORT,S1);
#define FREQ_SCAL_100p() GPIO_SetBits(Sx_PORT,S0);GPIO_SetBits(Sx_PORT,S1);

#define OUTPUT_RED() GPIO_ResetBits(Sx_PORT,S2);GPIO_ResetBits(Sx_PORT,S3);
#define OUTPUT_BLUE() GPIO_ResetBits(Sx_PORT,S2);GPIO_SetBits(Sx_PORT,S3);
#define OUTPUT_GREEN() GPIO_SetBits(Sx_PORT,S2);GPIO_SetBits(Sx_PORT,S3);

#define ENABLE_OUTPUT() GPIO_ResetBits(nOE_PORT,nOE);
#define DISABLE_OUTPUT() GPIO_SetBits(nOE_PORT,nOE);

#define SystemCoreClock 8000000 /*HSI frequency*/

/* Private variables */
GPIO_InitTypeDef gpio;
USART_InitTypeDef uart;
EXTI_InitTypeDef exti;
NVIC_InitTypeDef nvic;
TIM_TimeBaseInitTypeDef tim;
uint32_t ticks;
uint32_t scheduler;
uint8_t slope_count;
uint32_t period_meas;
uint32_t RED_values[5];
uint32_t RED_avr;
uint32_t BLUE_values[5];
uint32_t BLUE_avr;
uint32_t GREEN_values[5];
uint32_t GREEN_avr;
uint8_t table_indx;
char str[20];

/* Private function prototypes */
/* Private functions */
void GPIO_init(void);
void UART_init(void);
void RCC_init(void);
void NVIC_EXTI_init(void);
void TIM_init(void);
void delay_ms(uint32_t time_ms);
void send_char(char c);
void send_string(const char* s);
/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	/* PERIPHERAL INITIALIZATION */
	RCC_init();
	GPIO_init();
	UART_init();
	NVIC_EXTI_init();
	TIM_init();

	DISABLE_OUTPUT();
	FREQ_SCAL_2p();
	slope_count = 1;
	period_meas = 0;
	table_indx = 0;

	/*SysTick configuration*/
	if(SysTick_Config(SystemCoreClock / 1000)){
		send_string("E");send_string("\n\r");
		while(1);
	}
	send_string("S");send_string("\n\r");

  /**
  *  IMPORTANT NOTE!
  *  The symbol VECT_TAB_SRAM needs to be defined when building the project
  *  if code has been located to RAM and interrupts are used. 
  *  Otherwise the interrupt table located in flash will be used.
  *  See also the <system_*.c> file and how the SystemInit() function updates 
  *  SCB->VTOR register.  
  *  E.g.  SCB->VTOR = 0x20000000;  
  */
	while(1){
		ENABLE_OUTPUT();
		delay_ms(2);

		/* MEASURE RED */
		OUTPUT_RED();
		delay_ms(2);
		slope_count = 1;
		delay_ms(10);
		RED_values[table_indx] = period_meas;
		slope_count = 0;

		/* MEASURE BLUE */
		OUTPUT_BLUE();
		delay_ms(2);
		slope_count = 1;
		delay_ms(10);
		BLUE_values[table_indx] = period_meas;
		slope_count = 0;

		/* MEASURE GREEN */
		OUTPUT_GREEN();
		delay_ms(2);
		slope_count = 1;
		delay_ms(10);
		GREEN_values[table_indx] = period_meas;
		slope_count = 0;

		delay_ms(100);

		table_indx++;
		if(table_indx > 4){
			DISABLE_OUTPUT();
			/* CALCULATE AVERAGE VALUES */
			RED_avr = (RED_values[0] + RED_values[1] + RED_values[2] + RED_values[3] + RED_values[4]) / 5;
			BLUE_avr = (BLUE_values[0] + BLUE_values[1] + BLUE_values[2] + BLUE_values[3] + BLUE_values[4]) / 5;
			GREEN_avr = (GREEN_values[0] + GREEN_values[1] + GREEN_values[2] + GREEN_values[3] + GREEN_values[4]) / 5;
			table_indx = 0;


			sprintf(str, "%d", RED_avr); /* SEND RED DATA */
			send_string("R");send_string(str);send_string("\n\r");
			sprintf(str, "%d", BLUE_avr); /* SEND BLUE DATA */
			send_string("B");send_string(str);send_string("\n\r");
			sprintf(str, "%d", GREEN_avr); /* SEND GREEN DATA */
			send_string("G");send_string(str);send_string("\n\r");send_string("\n\r");

			delay_ms(1850);
		}



	}
}

/*
 * Interrupt handler.
 * Interrupt generated each rising edge at A4 pin.
 * */
void EXTI4_IRQHandler()
{
	/*First rising edge of the OUT signal*/
	if(slope_count == 1){
		TIM2 -> CNT = 0;
		slope_count = 2;
	/*Second rising edge of the OUT signal - period measurement*/
	}else if (slope_count == 2){
		period_meas = (TIM2 -> CNT);
		slope_count = 1;
	}else if(slope_count != 0){
		slope_count = 1;
	}

	EXTI_ClearITPendingBit(EXTI_Line4);
}

/*
 * SYSTICK used by delay_ms(uint32_t) function.
 * */
void SysTick_Handler()
{
    ticks++;
    //scheduler++;
}

void delay_ms(uint32_t time_ms){
	ticks = 0;
	while(ticks < time_ms);
}



void send_char(char c)
{
    while (USART_GetFlagStatus(USART2, USART_FLAG_TXE) == RESET);
    USART_SendData(USART2, c);
}



void send_string(const char* s)
{
    while (*s)
        send_char(*s++);
}


/* INITIALIZATION FUNCTIONS */
void GPIO_init(){
    /* UART CONFIG */
    /* UART TX */
    GPIO_StructInit(&gpio);
    gpio.GPIO_Pin = GPIO_Pin_2;
    gpio.GPIO_Mode = GPIO_Mode_AF_PP;
    GPIO_Init(GPIOA, &gpio);
    /* UART RX */
    gpio.GPIO_Pin = GPIO_Pin_3;
    gpio.GPIO_Mode = GPIO_Mode_IN_FLOATING;
    GPIO_Init(GPIOA, &gpio);

    /* OUT pin TCS3200D - interrupt generated at this pin */
    GPIO_StructInit(&gpio);
    gpio.GPIO_Pin = GPIO_Pin_4;
    gpio.GPIO_Mode = GPIO_Mode_IPD;
    GPIO_Init(GPIOA, &gpio);

    /* nOE pin TCS3200D - not used. Can be connected to LED pin of TCS3200D module. */
    GPIO_StructInit(&gpio);
    gpio.GPIO_Pin = GPIO_Pin_5;
    gpio.GPIO_Mode = GPIO_Mode_Out_PP;
    GPIO_Init(GPIOB, &gpio);

    /* S0 pin TCS3200D */
    GPIO_StructInit(&gpio);
    gpio.GPIO_Pin = GPIO_Pin_6;
    gpio.GPIO_Mode = GPIO_Mode_Out_PP;
    GPIO_Init(GPIOB, &gpio);

    /* S1 pin TCS3200D */
    GPIO_StructInit(&gpio);
    gpio.GPIO_Pin = GPIO_Pin_7;
    gpio.GPIO_Mode = GPIO_Mode_Out_PP;
    GPIO_Init(GPIOB, &gpio);

    /* S2 pin TCS3200D */
    GPIO_StructInit(&gpio);
    gpio.GPIO_Pin = GPIO_Pin_8;
    gpio.GPIO_Mode = GPIO_Mode_Out_PP;
    GPIO_Init(GPIOB, &gpio);

    /* S3 pin TCS3200D */
    GPIO_StructInit(&gpio);
    gpio.GPIO_Pin = GPIO_Pin_9;
    gpio.GPIO_Mode = GPIO_Mode_Out_PP;
    GPIO_Init(GPIOB, &gpio);


}

/*
 * UART2 initialization
 * */
void UART_init(){
	USART_StructInit(&uart);
	uart.USART_BaudRate = 9600;
	USART_Init(USART2, &uart);

	USART_Cmd(USART2, ENABLE);
}

/*
 * Clock configuration for all peripherals
 * */
void RCC_init(){
	RCC_SYSCLKConfig(RCC_SYSCLKSource_HSI); /* HSI 8MHz is a system clock*/

	RCC -> CFGR &= ~RCC_CFGR_PPRE1; /* APB1 prescaler = 1 */
	RCC -> CFGR &= ~RCC_CFGR_HPRE;  /* AHB prescaler = 1 */

    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA | RCC_APB2Periph_GPIOB, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO, ENABLE);
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART2, ENABLE);
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);
}

/*
 * Interrupt from TCS3200D OUT pin.
 * Interrupt is generated at each rising edge at OUT pin (A4 pin of the MCU).
 * */
void NVIC_EXTI_init(void){
	EXTI_StructInit(&exti);
	exti.EXTI_Line = EXTI_Line4;
	exti.EXTI_Mode = EXTI_Mode_Interrupt;
	exti.EXTI_Trigger = EXTI_Trigger_Rising;
	exti.EXTI_LineCmd = ENABLE;
	EXTI_Init(&exti);

	nvic.NVIC_IRQChannel = EXTI4_IRQn;
	nvic.NVIC_IRQChannelPreemptionPriority = 0x00;
	nvic.NVIC_IRQChannelSubPriority = 0x00;
	nvic.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&nvic);
}

/*
 * Timer used to measure signal's period at OUT output of TCS3200D sensor.
 * TIM2 is clocked with 1MHz frequency (1us period).
 * */
void TIM_init(void){
	TIM_TimeBaseStructInit(&tim);
	tim.TIM_CounterMode = TIM_CounterMode_Up;
	tim.TIM_Prescaler = 8;
	tim.TIM_Period = 65000 - 1;
	TIM_TimeBaseInit(TIM2, &tim);

	TIM_Cmd(TIM2, ENABLE);
}
